# docker-compose.yml
version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/model:/app/model   # Assurez-vous que le fichier de poids est présent
  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
