name: Backend CI/CD

on:
  push:
  pull_request:


jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Start FastAPI server
        working-directory: backend
        run: |
          nohup uvicorn app:app --host 127.0.0.1 --port 8000 --reload &
          sleep 5

      - name: Run tests
        working-directory: backend
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Build Docker image
        working-directory: backend
        run: |
            docker build -t ghcr.io/${GITHUB_REPOSITORY,,}/backend:latest .

      - name: Run Container Structure Tests for backend
        working-directory: backend
        run: |
          docker run --rm \
            -v $(pwd)/backend:/test \
            ghcr.io/googlecontainertools/container-structure-test:latest \
            test --image ghcr.io/${GITHUB_REPOSITORY,,}/backend:latest \
            --config container_structure_test_backend.yaml

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        working-directory: backend
        run: |
          docker push ghcr.io/${GITHUB_REPOSITORY,,}/backend:latest
