name: Frontend CI/CD

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        working-directory: frontend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        working-directory: frontend
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Build Docker image
        working-directory: frontend
        run: |
          docker build -t ghcr.io/${GITHUB_REPOSITORY,,}/frontend:latest .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        working-directory: frontend
        run: |
          docker push ghcr.io/${GITHUB_REPOSITORY,,}/frontend:latest
